//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tidred.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Customers = new HashSet<Customer>();
            this.PriceTypes = new HashSet<PriceType>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.WorkingSchedules = new HashSet<WorkingSchedule>();
        }
    
        public int CoID { get; set; }
        public string CoName { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<PriceType> PriceTypes { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<WorkingSchedule> WorkingSchedules { get; set; }
    }
}
