//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tidred.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public long CurrencyId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
