//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tidred.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceType
    {
        public PriceType()
        {
            this.TimeEntries = new HashSet<TimeEntry>();
            this.UserTimeEntryPrefs = new HashSet<UserTimeEntryPref>();
        }
    
        public long PriceTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CoID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<TimeEntry> TimeEntries { get; set; }
        public virtual ICollection<UserTimeEntryPref> UserTimeEntryPrefs { get; set; }
    }
}
