//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tidred.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.TimeEntries = new HashSet<TimeEntry>();
            this.UserTimeEntryPrefs = new HashSet<UserTimeEntryPref>();
        }
    
        public long ProjectId { get; set; }
        public string Name { get; set; }
        public long CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProjectFixedPrice ProjectFixedPrice { get; set; }
        public virtual ICollection<TimeEntry> TimeEntries { get; set; }
        public virtual ICollection<UserTimeEntryPref> UserTimeEntryPrefs { get; set; }
    }
}
