//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tidred.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTimeEntryPref
    {
        public string UserId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> PriceTypeId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PriceType PriceType { get; set; }
        public virtual Project Project { get; set; }
    }
}
