//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tidred.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingSchedule
    {
        public int Id { get; set; }
        public int CoId { get; set; }
        public int StartMonth { get; set; }
        public int EndMonth { get; set; }
        public decimal WorkingHours { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
